services:
  - type: web
    name: jaipur-kurti-gharana
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=400 --optimize-for-size
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
